//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//



@interface DOCKTileLayer

- (void)_setImage:(id)arg1;
- (id)addNamedImageLayer:(id)arg1 name:(id)arg2 atBottom:(_Bool)arg3;
- (void)_setReplacementExtraImage:(id)arg1;
@end

