//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

// Stripped down version to keep the vital minimum for building


@interface Tile : NSObject

- (void)setLabel:(id)arg1 stripAppSuffix:(_Bool)arg2;
- (void)setReplacementAppImage:(id)arg1;

@end

